name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.4
        
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      
    - name: List project files
      run: |
        echo "=== Project Structure ==="
        find . -type f -name "*.gradle" -o -name "*.xml" -o -name "*.java" -o -name "*.properties" | head -20
        echo "=== Gradle files ==="
        ls -la *.gradle || echo "No gradle files in root"
        ls -la app/*.gradle || echo "No gradle files in app"
        
    - name: Build with Gradle directly
      run: gradle assembleDebug --stacktrace --info
      
    - name: Find APK files
      run: |
        echo "=== Searching for APK files ==="
        find . -name "*.apk" -type f || echo "No APK files found"
        echo "=== Build outputs directory ==="
        find . -path "*/build/outputs*" -type d || echo "No build outputs found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: sponsored-detector-apk
        path: |
          app/build/outputs/apk/debug/*.apk
          **/build/outputs/apk/debug/*.apk
