name: Build Android APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Force Create Gradle Wrapper
      run: |
        # Remove any existing gradle files
        rm -rf gradle/wrapper
        rm -f gradlew gradlew.bat
        
        # Install Gradle directly
        wget https://services.gradle.org/distributions/gradle-8.4-bin.zip
        unzip -q gradle-8.4-bin.zip
        export PATH=$PATH:$PWD/gradle-8.4/bin
        
        # Generate wrapper using installed Gradle
        gradle wrapper --gradle-version 8.4
        
        # Verify wrapper was created
        ls -la gradlew
        ls -la gradle/wrapper/
        
        # Test wrapper
        ./gradlew --version
        
    - name: Create local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: sponsored-detector-apk
        path: app/build/outputs/apk/debug/*.apk
