name: Test Project

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check project structure
      run: |
        echo "=== Root files ==="
        ls -la
        echo "=== App directory ==="
        ls -la app/ || echo "No app directory"
        echo "=== Build gradle files ==="
        find . -name "build.gradle" -type f
        echo "=== Settings gradle ==="
        cat settings.gradle || echo "No settings.gradle"
        echo "=== App build.gradle ==="
        cat app/build.gradle || echo "No app/build.gradle"
